# Generated by Django 2.1.3 on 2018-12-07 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
        ('pub', '0001_initial'),
        ('cliente', '0001_initial'),
        ('hookah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.ClienteModel')),
                ('fk_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.FuncionarioModel')),
                ('fk_produto_hookah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hookah.ProdutoHookahModel')),
                ('fk_produto_pub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pub.ProdutoPubModel')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['fk_funcionario'],
            },
        ),
    ]
