# Generated by Django 2.1.3 on 2018-12-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0001_initial'),
        ('hookah', '0001_initial'),
        ('mesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidomodel',
            options={'ordering': ['id'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RenameField(
            model_name='pedidomodel',
            old_name='fk_cliente',
            new_name='Cliente',
        ),
        migrations.RenameField(
            model_name='pedidomodel',
            old_name='fk_funcionario',
            new_name='Funcionario',
        ),
        migrations.RemoveField(
            model_name='pedidomodel',
            name='fk_produto_hookah',
        ),
        migrations.RemoveField(
            model_name='pedidomodel',
            name='fk_produto_pub',
        ),
        migrations.AddField(
            model_name='pedidomodel',
            name='Produto_Hokaah',
            field=models.ManyToManyField(to='hookah.ProdutoHookahModel'),
        ),
        migrations.AddField(
            model_name='pedidomodel',
            name='Produto_Pub',
            field=models.ManyToManyField(to='pub.ProdutoPubModel'),
        ),
    ]
