# Generated by Django 2.1.2 on 2018-12-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0004_auto_20181207_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidomodel',
            old_name='Produto_Hokaah',
            new_name='Produto_Hookah',
        ),
    ]
